param(
  [string]$AnimalTablePath,
  [string]$AudioPolicyPath,
  [string]$SharedOutputPath,
  [string]$ManorOutputPath
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if (-not $AnimalTablePath) {
  $AnimalTablePath = Join-Path $repositoryRoot "docs\manor-assets\animals.csv"
}
if (-not $AudioPolicyPath) {
  $AudioPolicyPath = Join-Path $repositoryRoot "docs\manor-assets\animal-audio-policy.csv"
}
if (-not $ManorOutputPath) {
  $ManorOutputPath = Join-Path $repositoryRoot "packages\manor\src\animals.generated.ts"
}
if (-not $SharedOutputPath) {
  $SharedOutputPath = Join-Path $repositoryRoot "packages\shared\src\manor-animal-ids.generated.ts"
}
foreach ($path in @($AnimalTablePath, $AudioPolicyPath)) {
  if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
    throw "Required animal catalog source not found: $path"
  }
}

$audioPolicies = @{}
foreach ($policy in Import-Csv -LiteralPath $AudioPolicyPath) {
  $audioPolicies[[int]$policy.animal_id] = $policy
}

$animals = @(Import-Csv -LiteralPath $AnimalTablePath)
if ($animals.Count -ne 35) {
  throw "Expected 35 animal rows, found $($animals.Count)"
}

$runtimeAnimals = foreach ($animal in $animals) {
  $sourceId = [int]$animal.source_id
  $audioPolicy = $audioPolicies[$sourceId]
  if (-not $audioPolicy) {
    throw "Animal $sourceId is missing an audio policy"
  }
  $maturitySeconds = [int]$animal.maturity_seconds
  $productionSeconds = [int]$animal.production_seconds
  $cycleSeconds = [int]$animal.production_cycle_seconds
  $actionSeconds = [int]$animal.production_action_seconds
  if ($maturitySeconds -le 0 -or $productionSeconds -le 0 -or $cycleSeconds -le $actionSeconds) {
    throw "Animal $sourceId has an invalid lifecycle schedule"
  }
  [pscustomobject][ordered]@{
    sourceId = $sourceId
    name = $animal.name
    levelRequired = [int]$animal.original_level + 1
    category = if ($sourceId -gt 1500) { "shed" } else { "hutch" }
    purchasePrice = [int]$animal.purchase_price
    configuredAnimalSalePrice = [int]$animal.product_price
    animalSalePrice = [int]$animal.animal_sale_price
    animalHarvestExperience = [int]$animal.animal_harvest_experience
    animalUnit = $animal.animal_unit
    productionAction = $animal.production_action
    byproductName = $animal.byproduct_name
    configuredByproductSalePrice = [int]$animal.byproduct_price
    byproductSalePrice = [int]$animal.byproduct_sale_price
    byproductHarvestExperience = [int]$animal.byproduct_harvest_experience
    byproductUnit = $animal.byproduct_unit
    baseYield = [int]$animal.base_yield
    grassPerFourHours = [int]$animal.consume
    cubSeconds = [int]$animal.cub_seconds
    maturitySeconds = $maturitySeconds
    productionLifetimeSeconds = $productionSeconds
    lifecycleSeconds = $maturitySeconds + $productionSeconds
    productionCycleSeconds = $cycleSeconds
    productionActionSeconds = $actionSeconds
    description = $animal.description
    audioVariants = @($audioPolicy.available_variants -split ";" | Where-Object { $_ } | ForEach-Object { [int]$_ })
  }
}

if (@($runtimeAnimals | Select-Object -ExpandProperty sourceId -Unique).Count -ne 35) {
  throw "Runtime animal IDs are not unique"
}
if (@($runtimeAnimals | Where-Object category -eq "hutch").Count -ne 19) {
  throw "Expected 19 hutch animals"
}
if (@($runtimeAnimals | Where-Object category -eq "shed").Count -ne 16) {
  throw "Expected 16 shed animals"
}
if (@($runtimeAnimals | Where-Object { $_.audioVariants.Count -eq 0 }).Count -ne 2) {
  throw "Expected two animals without audio"
}

$manorJson = $runtimeAnimals | ConvertTo-Json -Depth 5
$sharedLines = [Collections.Generic.List[string]]::new()
$sharedLines.Add("// Generated by scripts/generate-manor-animal-catalog.ps1. Do not edit manually.")
$sharedLines.Add("export const MANOR_ANIMAL_SOURCE_IDS = [")
foreach ($sourceId in @($runtimeAnimals | Select-Object -ExpandProperty sourceId)) {
  $sharedLines.Add("  $sourceId,")
}
$sharedLines.Add("] as const;")
$sharedLines.Add("")
Set-Content -LiteralPath $SharedOutputPath -Value $sharedLines -Encoding utf8

$manorSource = @"
// Generated by scripts/generate-manor-animal-catalog.ps1. Do not edit manually.
export const MANOR_ANIMAL_DATA = $manorJson as const;
"@
Set-Content -LiteralPath $ManorOutputPath -Value $manorSource -Encoding utf8

[pscustomobject]@{
  Animals = $runtimeAnimals.Count
  HutchAnimals = @($runtimeAnimals | Where-Object category -eq "hutch").Count
  ShedAnimals = @($runtimeAnimals | Where-Object category -eq "shed").Count
  WithoutAudio = @($runtimeAnimals | Where-Object { $_.audioVariants.Count -eq 0 }).Count
  SharedOutput = $SharedOutputPath
  ManorOutput = $ManorOutputPath
}
