param(
  [string]$DecorationTablePath,
  [string]$RuntimeMappingPath,
  [string]$OutputPath
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if (-not $DecorationTablePath) {
  $DecorationTablePath = Join-Path $repositoryRoot "docs\manor-assets\decorations.csv"
}
if (-not $RuntimeMappingPath) {
  $RuntimeMappingPath = Join-Path $repositoryRoot "docs\manor-assets\decoration-runtime-assets.csv"
}
if (-not $OutputPath) {
  $OutputPath = Join-Path $repositoryRoot "packages\manor\src\decorations.generated.ts"
}
foreach ($path in @($DecorationTablePath, $RuntimeMappingPath)) {
  if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
    throw "Required decoration catalog source not found: $path"
  }
}

$runtimeById = @{}
foreach ($asset in Import-Csv -LiteralPath $RuntimeMappingPath) {
  $runtimeById[[int]$asset.source_id] = $asset
}

$items = foreach ($decoration in Import-Csv -LiteralPath $DecorationTablePath) {
  if ($decoration.integration_policy -ne "default") { continue }
  $sourceId = [int]$decoration.source_id
  $runtime = $runtimeById[$sourceId]
  if (-not $runtime) { throw "Decoration $sourceId is missing a runtime asset" }
  $runtimeAsset = "/" + ($runtime.runtime_asset -replace '^apps/web/public/', '')
  $runtimeThumbnail = "/" + ($runtime.runtime_thumbnail -replace '^apps/web/public/', '')
  [pscustomobject][ordered]@{
    sourceId = $sourceId
    name = $decoration.name
    setName = $decoration.set_name
    category = $decoration.item_type_name
    levelRequired = [int]$decoration.original_level + 1
    coinPrice = [int]$decoration.coin_price
    experience = [int]$decoration.experience
    validSeconds = [int]$decoration.valid_seconds
    purchasable = [int]$decoration.coin_price -gt 1
    width = [int]$runtime.width
    height = [int]$runtime.height
    assetUrl = $runtimeAsset
    thumbnailUrl = $runtimeThumbnail
  }
}

$items = @($items | Sort-Object sourceId)
if ($items.Count -ne 162) { throw "Expected 162 decoration catalog items, found $($items.Count)" }
if (@($items | Where-Object purchasable).Count -ne 142) { throw "Expected 142 purchasable decorations" }

$json = $items | ConvertTo-Json -Depth 4
$source = @"
// Generated by scripts/generate-manor-decoration-catalog.ps1. Do not edit manually.
export const MANOR_DECORATION_DATA = $json as const;
"@
Set-Content -LiteralPath $OutputPath -Value $source -Encoding utf8

[pscustomobject]@{
  Decorations = $items.Count
  Purchasable = @($items | Where-Object purchasable).Count
  ActivityOnly = @($items | Where-Object { -not $_.purchasable }).Count
  Output = $OutputPath
}
