param(
  [string]$LegacyRoot,
  [string]$CropTablePath,
  [string]$SharedOutputPath,
  [string]$ManorOutputPath
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if (-not $LegacyRoot) {
  $LegacyRoot = Join-Path $repositoryRoot "..\..\20_ThirdParty\qqfarm\upload\home\qqfarm"
}
$LegacyRoot = (Resolve-Path $LegacyRoot).Path
if (-not $CropTablePath) {
  $CropTablePath = Join-Path $repositoryRoot "docs\manor-assets\crops.csv"
}
if (-not $SharedOutputPath) {
  $SharedOutputPath = Join-Path $repositoryRoot "packages\shared\src\manor-crop-ids.generated.ts"
}
if (-not $ManorOutputPath) {
  $ManorOutputPath = Join-Path $repositoryRoot "packages\manor\src\crops.generated.ts"
}

$cropTimePath = Join-Path $LegacyRoot "source\nc\config\cropstime.php"
$hidePath = Join-Path $LegacyRoot "data\hide.php"
foreach ($path in @($CropTablePath, $cropTimePath, $hidePath)) {
  if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
    throw "Required crop source not found: $path"
  }
}

$cropTimes = @{}
$cropTimeSource = Get-Content -LiteralPath $cropTimePath -Raw
$cropTimePattern = '"(?<id>\d+)"\s*=>\s*array\((?<values>[\d,\s]+)\)'
foreach ($match in [regex]::Matches($cropTimeSource, $cropTimePattern)) {
  $values = @($match.Groups["values"].Value -split "," | ForEach-Object { [int]$_.Trim() })
  if ($values.Count -lt 5) {
    throw "Crop $($match.Groups['id'].Value) has an incomplete growth schedule"
  }
  $cropTimes[[int]$match.Groups["id"].Value] = $values
}

$hideSource = Get-Content -LiteralPath $hidePath -Raw
$hideMatch = [regex]::Match($hideSource, '\$_HIDE\[''seed''\]\s*=\s*array\((?<ids>[^)]*)\)')
if (-not $hideMatch.Success) {
  throw "Hidden seed list was not found in $hidePath"
}
$hiddenSeedIds = [Collections.Generic.HashSet[int]]::new()
foreach ($id in $hideMatch.Groups["ids"].Value -split ",") {
  [void]$hiddenSeedIds.Add([int]$id.Trim())
}

$crops = @(Import-Csv -LiteralPath $CropTablePath)
if ($crops.Count -ne 86) {
  throw "Expected 86 crop rows, found $($crops.Count)"
}
if ($hiddenSeedIds.Count -ne 29) {
  throw "Expected 29 hidden seed IDs, found $($hiddenSeedIds.Count)"
}

$runtimeCrops = foreach ($crop in $crops) {
  $sourceId = [int]$crop.source_id
  if (-not $cropTimes.ContainsKey($sourceId)) {
    throw "Crop $sourceId is missing from cropstime.php"
  }
  $growthSeconds = [int]$crop.growth_seconds
  $regrowthSeconds = $growthSeconds - [int]$cropTimes[$sourceId][2]
  if ($regrowthSeconds -le 0) {
    throw "Crop $sourceId has an invalid regrowth duration"
  }
  $id = if ($crop.current_id) { $crop.current_id } else { "legacy-$sourceId" }
  [ordered]@{
    id = $id
    sourceId = $sourceId
    name = $crop.name
    emoji = $crop.name.Substring(0, 1)
    levelRequired = [int]$crop.original_level + 1
    seedPrice = [int]$crop.seed_price
    salePrice = [int]$crop.sale_price
    growthSeconds = $growthSeconds
    regrowthSeconds = $regrowthSeconds
    baseYield = [int]$crop.base_yield
    experience = [int]$crop.experience
    harvestCycles = [int]$crop.harvest_cycles
    purchasable = -not $hiddenSeedIds.Contains($sourceId)
  }
}

$runtimeIds = @($runtimeCrops | ForEach-Object { $_.id })
if (@($runtimeIds | Select-Object -Unique).Count -ne 86) {
  throw "Runtime crop IDs are not unique"
}
if (@($runtimeCrops | Where-Object purchasable).Count -ne 57) {
  throw "Expected 57 purchasable crops"
}

$sharedLines = [Collections.Generic.List[string]]::new()
$sharedLines.Add("// Generated by scripts/generate-manor-crop-catalog.ps1. Do not edit manually.")
$sharedLines.Add("export const MANOR_CROP_IDS = [")
foreach ($id in $runtimeIds) {
  $sharedLines.Add("  `"$id`",")
}
$sharedLines.Add("] as const;")
$sharedLines.Add("")
Set-Content -LiteralPath $SharedOutputPath -Value $sharedLines -Encoding utf8

$manorJson = $runtimeCrops | ConvertTo-Json -Depth 4
$manorSource = @"
// Generated by scripts/generate-manor-crop-catalog.ps1. Do not edit manually.
export const MANOR_CROP_DATA = $manorJson as const;
"@
Set-Content -LiteralPath $ManorOutputPath -Value $manorSource -Encoding utf8

[pscustomobject]@{
  Crops = $runtimeCrops.Count
  Purchasable = @($runtimeCrops | Where-Object purchasable).Count
  Hidden = @($runtimeCrops | Where-Object { -not $_.purchasable }).Count
  SharedOutput = $SharedOutputPath
  ManorOutput = $ManorOutputPath
}
